# Generated by Django 3.2.1 on 2022-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0002_historicalluggageavailablecode_historicaltest_historicaltestsearchrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='document_type',
            field=models.CharField(choices=[('dni', 'Dni'), ('passport', 'Pasaporte'), ('ce', 'Carnet de extranjeria'), ('rn', 'Recien nacido'), ('pn', 'Partida de nacimiento'), ('pdp', 'Paciente con datos protegidos'), ('ot', 'Otros')], default='dni', max_length=40, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_type',
            field=models.CharField(choices=[('dni', 'Dni'), ('passport', 'Pasaporte'), ('ce', 'Carnet de extranjeria'), ('rn', 'Recien nacido'), ('pn', 'Partida de nacimiento'), ('pdp', 'Paciente con datos protegidos'), ('ot', 'Otros')], default='dni', max_length=40, verbose_name='Tipo de documento'),
        ),
    ]
