# Generated by Django 3.2.1 on 2022-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0003_auto_20220511_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalluggage',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='luggage/image', verbose_name='Imagen'),
        ),
    ]
