# Generated by Django 3.2.1 on 2024-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0004_auto_20220516_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalluggage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Valija', 'verbose_name_plural': 'historical Valija'},
        ),
        migrations.AlterModelOptions(
            name='historicalluggageavailablecode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Código', 'verbose_name_plural': 'historical Códigos'},
        ),
        migrations.AlterModelOptions(
            name='historicalluggagedetail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Valija detalle', 'verbose_name_plural': 'historical Valija detalles'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Paciente', 'verbose_name_plural': 'historical Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='historicaltest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prueba', 'verbose_name_plural': 'historical Pruebas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltestsearchrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical test search record', 'verbose_name_plural': 'historical test search records'},
        ),
        migrations.AlterField(
            model_name='historicalluggage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalluggageavailablecode',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalluggagedetail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltestsearchrecord',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
