# Generated by Django 3.2.1 on 2022-05-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('luggage', '0058_alter_luggage_reference'),
    ]

    operations = []
