# Generated by Django 3.2.1 on 2022-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0059_auto_20220504_1134'),
    ]

    operations = [
    ]
