# Generated by Django 3.2.25 on 2025-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0061_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalluggage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Valija'},
        ),
        migrations.AlterModelOptions(
            name='historicalluggageavailablecode',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Código'},
        ),
        migrations.AlterModelOptions(
            name='historicalluggagedetail',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Valija detalle'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Paciente'},
        ),
        migrations.AlterModelOptions(
            name='historicaltest',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prueba'},
        ),
        migrations.AlterModelOptions(
            name='historicaltestsearchrecord',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical test search record'},
        ),
        migrations.AlterField(
            model_name='historicalluggage',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalluggageavailablecode',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalluggagedetail',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltest',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltestsearchrecord',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
