# Generated by Django 3.2.1 on 2022-03-31 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_remove_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('name', models.CharField(max_length=6, unique_for_date='date', verbose_name='Nombre')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('last_id', models.BigIntegerField(verbose_name='Último ID actualizado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Referencias',
                'verbose_name_plural': 'Referencias enviadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnilabsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='* Nombre')),
                ('type', models.SmallIntegerField(choices=[(1, 'Sesiones por Referencia'), (2, 'Valijas por Referencia')], verbose_name='* Tipo')),
                ('type_date', models.SmallIntegerField(choices=[(1, 'Hora'), (2, 'Día'), (3, 'Mes'), (4, 'Año')], default=2, verbose_name='* Agrupado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación (inicio)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación (fin)')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Descargable')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_customer_report', to='users.reference', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('luggage_pdf', 'Valija PDF'), ('luggage_excel', 'Valija Excel')], default='pdf', max_length=40, null=True, verbose_name='Tipo')),
                ('params', models.CharField(blank=True, max_length=200, null=True, verbose_name='Parametros')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creación')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_result_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Tracking',
            },
        ),
    ]
