# Generated by Django 3.2.1 on 2022-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilabsreport',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Sesiones por Referencia'), (2, 'Valijas por Referencia'), (3, 'Referencias por Usuario'), (4, 'Resultados no descargados'), (5, 'Imagenes no descargadas')], verbose_name='* Tipo'),
        ),
    ]
