# Generated by Django 3.2.1 on 2022-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_unilabsreport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='type',
            field=models.CharField(choices=[('luggage_pdf', 'Valija PDF'), ('luggage_excel', 'Valija Excel'), ('result_pdf', 'Resultado PDF'), ('image_pdf', 'Imagen PDF')], default='pdf', max_length=40, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='unilabsreport',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Sesiones por Referencia'), (2, 'Valijas por Referencia'), (3, 'Referencias por Usuario'), (4, 'Resultados no descargados'), (5, 'Imagenes no descargadas'), (6, 'Usuarios no usan la aplicación')], verbose_name='* Tipo'),
        ),
    ]
