# Generated by Django 3.2.1 on 2022-05-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220520_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilabsreport',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Sesiones por Referencia'), (2, 'Valijas por Referencia'), (3, 'Referencias por Usuario'), (4, 'Reporte de resultados no descargados'), (5, 'Reporte de imagenes no descargadas'), (6, 'Usuarios no usan la aplicación')], verbose_name='* Tipo'),
        ),
    ]
