# Generated by Django 3.2.1 on 2022-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_unilabsreport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilabsreport',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Fecha de aprobación (fin)'),
        ),
        migrations.AlterField(
            model_name='unilabsreport',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Fecha de aprobación (inicio)'),
        ),
    ]
