# Generated by Django 3.2.1 on 2022-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20220524_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilabsreport',
            name='end_date',
            field=models.DateField(default=None, verbose_name='Fecha de aprobación (fin)'),
        ),
        migrations.AlterField(
            model_name='unilabsreport',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Fecha de aprobación (inicio)'),
        ),
    ]
