# Generated by Django 3.2.1 on 2022-03-31 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=70, null=True, unique=True, verbose_name='ID Image ref')),
                ('name', models.CharField(max_length=70, null=True, unique=True, verbose_name='Cliente')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('code', models.CharField(max_length=20, null=True, unique=True, verbose_name='Código')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=70, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=None, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Cantidad onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_finish',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Onboarding finalizado'),
        ),
        migrations.AddField(
            model_name='user',
            name='sync',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Sincronizar?'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None, verbose_name='Último inicio'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='origenes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to='users.reference', to_field='code', verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(related_name='references', to='users.Reference', verbose_name='Referencias'),
        ),
    ]
