# Generated by Django 3.2.1 on 2022-03-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
