# Generated by Django 3.2.1 on 2022-03-31 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220331_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='origenes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to='users.reference', to_field='code', verbose_name='Referencia'),
        ),
    ]
