# Generated by Django 3.2.1 on 2022-04-05 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20220404_2329'),
        ('users', '0007_alter_user_origenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Unilabs', max_length=30, verbose_name='Tipo de usuario'),
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_user', to='setting.module', verbose_name='Modulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_module', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='ReferenceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_multiple_reference', to='users.reference', to_field='code', verbose_name='Referencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_multiple_reference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ejecutivo',
                'verbose_name_plural': 'Ejectivo',
            },
        ),
        migrations.CreateModel(
            name='ReferenceExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive_reference', to='users.reference', to_field='code', verbose_name='Referencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_reference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ejecutivo',
                'verbose_name_plural': 'Ejectivo',
            },
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True, unique=True, verbose_name='Cliente')),
                ('reference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts_reference', to='users.reference', to_field='code', verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['name'],
            },
        ),
    ]
