# Generated by Django 3.2.1 on 2022-04-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20220404_2329'),
        ('users', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(related_name='modules', to='setting.Module', verbose_name='Modulos'),
        ),
    ]
