# Generated by Django 3.2.1 on 2022-04-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='usermodule',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferenceUser',
        ),
        migrations.DeleteModel(
            name='UserModule',
        ),
    ]
