# Generated by Django 3.2.1 on 2022-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=30, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
    ]
