# Generated by Django 3.2.1 on 2022-04-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220405_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='modules',
            new_name='access',
        ),
    ]
