# Generated by Django 3.2.1 on 2022-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_modules_user_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AddField(
            model_name='user',
            name='code_activation',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='code'),
        ),
    ]
