# Generated by Django 3.2.1 on 2022-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220407_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_activation',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Token activación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_activation',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código activación'),
        ),
    ]
