# Generated by Django 3.2.1 on 2022-04-12 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220407_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_admin', to='users.reference', to_field='code', verbose_name='Referencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
