# Generated by Django 3.2.1 on 2022-04-12 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_referenceadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceadmin',
            name='reference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_reference_admin', to='users.reference', to_field='code', verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='referenceadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reference_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='origenes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to='users.reference', to_field='code', verbose_name='Referencia (activa)'),
        ),
    ]
