# Generated by Django 3.2.1 on 2025-05-21 14:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    replaces = [('users', '0018_auto_20220412_0941'), ('users', '0019_user_email_activated'), ('users', '0020_auto_20220419_1011'), ('users', '0021_remove_reference_manager'), ('users', '0022_auto_20220420_1830'), ('users', '0023_alter_user_is_staff'), ('users', '0024_alter_user_username'), ('users', '0025_auto_20220421_1810'), ('users', '0026_alter_reference_motive'), ('users', '0027_user_is_admin_bk'), ('users', '0028_auto_20220422_1629'), ('users', '0029_alter_user_is_admin_bk'), ('users', '0030_reference_created'), ('users', '0031_alter_user_username'), ('users', '0032_alter_user_username'), ('users', '0033_alter_referenceexecutive_user'), ('users', '0034_user_updated'), ('users', '0035_auto_20220425_0103'), ('users', '0036_auto_20220425_0108'), ('users', '0037_auto_20220425_0127'), ('users', '0038_auto_20220510_0831'), ('users', '0039_auto_20220511_1108'), ('users', '0040_auto_20220511_1116'), ('users', '0041_auto_20220511_1212'), ('users', '0042_auto_20220512_1523'), ('users', '0043_auto_20220512_1554'), ('users', '0044_auto_20220512_1555'), ('users', '0045_auto_20220512_1619'), ('users', '0046_auto_20220516_1527'), ('users', '0047_auto_20220516_1601'), ('users', '0048_auto_20220516_2224'), ('users', '0049_auto_20220517_0938'), ('users', '0050_auto_20220518_1027'), ('users', '0051_auto_20220518_1056'), ('users', '0052_auto_20220518_1103'), ('users', '0053_auto_20220518_1243'), ('users', '0054_auto_20220518_1250'), ('users', '0055_auto_20220518_1842'), ('users', '0056_auto_20220519_1023'), ('users', '0057_auto_20220519_1718'), ('users', '0058_auto_20220519_1804'), ('users', '0059_auto_20220520_0026'), ('users', '0060_auto_20220520_0149'), ('users', '0061_auto_20220520_1115'), ('users', '0062_auto_20220520_1119'), ('users', '0063_auto_20220520_1121'), ('users', '0064_auto_20220523_1507'), ('users', '0065_auto_20220524_1147'), ('users', '0066_auto_20220524_1149'), ('users', '0067_auto_20220524_1151'), ('users', '0068_auto_20220525_2349'), ('users', '0069_auto_20220525_2355'), ('users', '0070_auto_20220526_0005'), ('users', '0071_auto_20220526_0841'), ('users', '0072_auto_20220601_2135'), ('users', '0073_auto_20220601_2136'), ('users', '0074_auto_20220601_2144'), ('users', '0075_auto_20220601_2148'), ('users', '0076_auto_20220603_1800'), ('users', '0077_auto_20220603_1814'), ('users', '0078_auto_20220607_1212'), ('users', '0079_auto_20220607_1247'), ('users', '0080_auto_20220610_1008'), ('users', '0081_auto_20220610_1010'), ('users', '0082_auto_20240816_1311')]

    dependencies = [
        ('users', '0017_referenceadmin'),
        ('setting', '0010_module_icon_image'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceadmin',
            name='reference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_reference_admin', to='users.reference', to_field='code', verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='referenceadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reference_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='origenes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to='users.reference', to_field='code', verbose_name='Referencia (activa)'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_activated',
            field=models.BooleanField(default=False, verbose_name='Email activado'),
        ),
        migrations.AlterModelOptions(
            name='referenceexecutive',
            options={'verbose_name': 'Ejecutivo', 'verbose_name_plural': 'Ejecutivos'},
        ),
        migrations.AddField(
            model_name='reference',
            name='active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='reference',
            name='document_type_manager',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='reference',
            name='description_siglo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción siglo'),
        ),
        migrations.AddField(
            model_name='reference',
            name='document_number_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='reference',
            name='last_name_manager',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del responsable'),
        ),
        migrations.AddField(
            model_name='reference',
            name='name_manager',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres del responsable'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='origenes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to='users.reference', to_field='code', verbose_name='Referencia (activa)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='reference',
            name='motive',
            field=models.TextField(max_length=400, null=True, verbose_name='Motivo (activación/desactivación)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(blank=True, default=None, related_name='modules', to='setting.Module', verbose_name='Modulos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(blank=True, default=None, related_name='references', to='users.Reference', verbose_name='Referencias'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_bk',
            field=models.BooleanField(default=False, verbose_name='¿Admin backoffice?'),
        ),
        migrations.AddField(
            model_name='reference',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, null=True, unique=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='referenceexecutive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_user_reference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 16, 13, 11, 18, 300282), null=True, verbose_name='Última de modificación'),
        ),
        migrations.CreateModel(
            name='HistoricalReferenceExecutive',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.reference', to_field='code', verbose_name='Referencia')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Ejecutivo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
                'verbose_name_plural': 'historical Ejecutivos',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReferenceAdmin',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.reference', to_field='code', verbose_name='Referencia')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'historical Administrador',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
                'verbose_name_plural': 'historical Administradores',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='references', to='users.Reference', verbose_name='Referencias'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_password',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Contraseña cambiada?'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='reference_active',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_session', to='users.reference', verbose_name='Referencia'),
        ),
        migrations.CreateModel(
            name='UserLogPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación')),
                ('user_changed', models.CharField(max_length=150, verbose_name='Usuario (admin)')),
                ('user_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log_password', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log password',
                'verbose_name_plural': 'Logs password',
            },
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=70, unique=True, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='HistoricalReference',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Cliente')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('code', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Código')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('description_siglo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción siglo')),
                ('name_manager', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres del responsable')),
                ('last_name_manager', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del responsable')),
                ('document_type_manager', models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='', max_length=30, verbose_name='Tipo de documento')),
                ('document_number_manager', models.CharField(blank=True, max_length=70, null=True, verbose_name='Documento')),
                ('active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('motive', models.TextField(max_length=400, null=True, verbose_name='Motivo (activación/desactivación)')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Referencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
                'verbose_name_plural': 'historical Referencias',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default='Dni', max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=30, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='user',
            name='encript_password',
            field=models.BooleanField(default=False, verbose_name='Encript password'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_password_from_bkoffice',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Contraseña desde backoffice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Último inicio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None, null=True, verbose_name='Último inicio'),
        ),
        migrations.CreateModel(
            name='GroupsAdmin',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('type', models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name_plural': 'Roles y permisos',
                'ordering': ['name'],
            },
            bases=('auth.group',),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='Dni', max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=250, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_activation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Token activación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=30, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=150, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default=None, max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Tipo de usuario')),
                ('username', models.CharField(db_index=True, max_length=70, verbose_name='Usuario')),
                ('email', models.EmailField(db_index=True, default=None, max_length=250, null=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Apellidos')),
                ('code_activation', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código activación')),
                ('token_activation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Token activación')),
                ('job', models.CharField(max_length=150, null=True, verbose_name='Puesto')),
                ('cellphone', models.CharField(max_length=15, null=True, verbose_name='Celular')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=30, null=True, verbose_name='Sexo')),
                ('document_type', models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default=None, max_length=30, null=True, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Documento')),
                ('onboarding_count', models.IntegerField(default=0, null=True, verbose_name='Cantidad onboarding')),
                ('onboarding', models.BooleanField(blank=True, default=False, null=True, verbose_name='Onboarding')),
                ('onboarding_finish', models.BooleanField(blank=True, default=False, null=True, verbose_name='Onboarding finalizado')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 8, 16, 13, 11, 18, 300282), null=True, verbose_name='Última de modificación')),
                ('last_login', models.DateTimeField(default=None, null=True, verbose_name='Último inicio')),
                ('sync', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Sincronizar?')),
                ('email_activated', models.BooleanField(default=False, verbose_name='Email activado')),
                ('verify_token', models.CharField(blank=True, max_length=400, null=True, verbose_name='Token verify')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('is_admin_bk', models.BooleanField(default=False, verbose_name='¿Admin backoffice?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origenes', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.reference', to_field='code', verbose_name='Referencia (activa)')),
                ('update_password', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Contraseña cambiada?')),
                ('encript_password', models.BooleanField(default=False, verbose_name='Encript password')),
                ('update_password_from_bkoffice', models.BooleanField(blank=True, default=False, null=True, verbose_name='Contraseña desde backoffice')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
                'verbose_name_plural': 'historical Usuarios',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Synchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación')),
                ('is_ok', models.BooleanField(default=True, verbose_name='Correcto')),
                ('type', models.CharField(choices=[('Usuarios', 'Usuarios'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Cron')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Sincronización',
                'verbose_name_plural': 'Sincronizaciones',
            },
        ),
    ]
