# Generated by Django 3.2.1 on 2022-04-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220412_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_activated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Email activado'),
        ),
    ]
