# Generated by Django 3.2.1 on 2022-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('loggeduser', '0018_auto_20220331_1817'),
    ]

    operations = [
    ]
