# Generated by Django 3.2.1 on 2022-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('loggeduser', '0019_loggeduser_change_password'),
    ]

    operations = [
    ]
