# Generated by Django 3.2.1 on 2022-04-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_email_activated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenceexecutive',
            options={'verbose_name': 'Ejecutivo', 'verbose_name_plural': 'Ejecutivos'},
        ),
        migrations.AddField(
            model_name='reference',
            name='active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='reference',
            name='description_siglo',
            field=models.CharField(max_length=70, null=True, verbose_name='Descripción siglo'),
        ),
        migrations.AddField(
            model_name='reference',
            name='document_number_manager',
            field=models.CharField(max_length=70, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='reference',
            name='document_type_manager',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default='Dni', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='reference',
            name='last_name_manager',
            field=models.CharField(max_length=70, null=True, verbose_name='Apellidos del responsable'),
        ),
        migrations.AddField(
            model_name='reference',
            name='manager',
            field=models.CharField(max_length=70, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='reference',
            name='name_manager',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombres del responsable'),
        ),
    ]
