# Generated by Django 3.2.1 on 2022-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('loggeduser', '0020_alter_loggeduser_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=150, null=True, verbose_name='Telefono'),
        ),
    ]
