# Generated by Django 3.2.1 on 2022-04-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220419_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='manager',
        ),
    ]
