# Generated by Django 3.2.1 on 2022-04-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_reference_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='description_siglo',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Descripción siglo'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='document_number_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='last_name_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Apellidos del responsable'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombres del responsable'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='origenes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reference', to='users.reference', to_field='code', verbose_name='Referencia (activa)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Tipo de usuario'),
        ),
    ]
