# Generated by Django 3.2.1 on 2022-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('loggeduser', '0021_auto_20220509_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(max_length=20, null=True, verbose_name='RUC'),
        ),
    ]
