# Generated by Django 3.2.1 on 2022-05-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('loggeduser', '0022_auto_20220509_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, unique=False, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='RUC'),
        ),
    ]
