# Generated by Django 3.2.1 on 2022-05-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('loggeduser', '0023_auto_20220509_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='code',
            field=models.CharField(default=None, max_length=150, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(default=None, max_length=150, null=True, unique=False, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(default=None, null=True, max_length=150, verbose_name='RUC'),
        ),
    ]
