# Generated by Django 3.2.1 on 2022-04-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='motive',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
