# Generated by Django 3.2.1 on 2022-04-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220421_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='motive',
            field=models.TextField(max_length=400, null=True, verbose_name='Motivo'),
        ),
    ]
