# Generated by Django 3.2.1 on 2022-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_reference_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_bk',
            field=models.BooleanField(default=True, verbose_name='¿Admin backoffice?'),
        ),
    ]
