# Generated by Django 3.2.1 on 2022-04-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_module_icon_image'),
        ('users', '0027_user_is_admin_bk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(blank=True, default=None, related_name='modules', to='setting.Module', verbose_name='Modulos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(blank=True, default=None, related_name='references', to='users.Reference', verbose_name='Referencias'),
        ),
    ]
