# Generated by Django 3.2.1 on 2022-04-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_reference_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, null=True, unique=True, verbose_name='Usuario'),
        ),
    ]
