# Generated by Django 3.2.1 on 2022-04-25 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceexecutive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_user_reference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
