# Generated by Django 3.2.1 on 2022-04-25 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_referenceexecutive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 22, 47, 19, 996452), null=True, verbose_name='Última de modificación'),
        ),
    ]
