# Generated by Django 3.2.1 on 2022-04-25 06:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 1, 3, 26, 860691), null=True, verbose_name='Última de modificación'),
        ),
        migrations.CreateModel(
            name='HistoricalReference',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70, null=True, verbose_name='Cliente')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('code', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Código')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=70, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección')),
                ('description_siglo', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descripción siglo')),
                ('name_manager', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombres del responsable')),
                ('last_name_manager', models.CharField(blank=True, max_length=70, null=True, verbose_name='Apellidos del responsable')),
                ('document_type_manager', models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default='Dni', max_length=30, verbose_name='Tipo de documento')),
                ('document_number_manager', models.CharField(blank=True, max_length=70, null=True, verbose_name='Documento')),
                ('active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('motive', models.TextField(max_length=400, null=True, verbose_name='Motivo')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Referencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
