# Generated by Django 3.2.1 on 2022-04-25 06:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20220425_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 1, 8, 4, 94362), null=True, verbose_name='Última de modificación'),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Tipo de usuario')),
                ('username', models.CharField(db_index=True, max_length=45, verbose_name='Usuario')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('code_activation', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código activación')),
                ('token_activation', models.CharField(blank=True, max_length=140, null=True, verbose_name='Token activación')),
                ('job', models.CharField(blank=True, max_length=150, null=True, verbose_name='Puesto')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=30, verbose_name='Sexo')),
                ('document_type', models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default='Dni', max_length=30, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Documento')),
                ('onboarding_count', models.IntegerField(default=0, null=True, verbose_name='Cantidad onboarding')),
                ('onboarding', models.BooleanField(blank=True, default=False, null=True, verbose_name='Onboarding')),
                ('onboarding_finish', models.BooleanField(blank=True, default=False, null=True, verbose_name='Onboarding finalizado')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 4, 25, 1, 8, 4, 94362), null=True, verbose_name='Última de modificación')),
                ('last_login', models.DateTimeField(blank=True, editable=False, verbose_name='Último inicio')),
                ('sync', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Sincronizar?')),
                ('email_activated', models.BooleanField(blank=True, default=False, null=True, verbose_name='Email activado')),
                ('verify_token', models.CharField(blank=True, max_length=400, null=True, verbose_name='Token verify')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('is_admin_bk', models.BooleanField(default=False, verbose_name='¿Admin backoffice?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origenes', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.reference', to_field='code', verbose_name='Referencia (activa)')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
