# Generated by Django 3.2.1 on 2022-05-10 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20220425_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='motive',
            field=models.TextField(max_length=400, null=True, verbose_name='Motivo (activación/desactivación)'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 31, 8, 163825), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='motive',
            field=models.TextField(max_length=400, null=True, verbose_name='Motivo (activación/desactivación)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 31, 8, 163825), null=True, verbose_name='Última de modificación'),
        ),
    ]
