# Generated by Django 3.2.1 on 2022-05-11 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20220511_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 11, 16, 27, 898507), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='references', to='users.Reference', verbose_name='Referencias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 11, 16, 27, 898507), null=True, verbose_name='Última de modificación'),
        ),
    ]
