# Generated by Django 3.2.1 on 2022-05-11 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20220511_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='update_password',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Contraseña cambiada?'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_password',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Contraseña cambiada?'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 12, 12, 39, 111173), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 12, 12, 39, 111173), null=True, verbose_name='Última de modificación'),
        ),
    ]
