# Generated by Django 3.2.1 on 2022-05-12 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20220511_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 15, 22, 59, 3286), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 15, 22, 59, 3286), null=True, verbose_name='Última de modificación'),
        ),
    ]
