# Generated by Django 3.2.1 on 2022-05-12 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20220512_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 16, 19, 3, 374497), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 16, 19, 3, 374497), null=True, verbose_name='Última de modificación'),
        ),
    ]
