# Generated by Django 3.2.1 on 2022-05-16 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20220516_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='reference_active',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_session', to='users.reference', verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 1, 43, 269941), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 1, 43, 269941), null=True, verbose_name='Última de modificación'),
        ),
    ]
