# Generated by Django 3.2.1 on 2022-05-17 03:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20220516_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 24, 43, 543778), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 24, 43, 543778), null=True, verbose_name='Última de modificación'),
        ),
        migrations.CreateModel(
            name='UserLogPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación')),
                ('user_changed', models.CharField(max_length=150, verbose_name='Usuario (admin)')),
                ('user_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log_password', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log password',
                'verbose_name_plural': 'Log password',
            },
        ),
    ]
