# Generated by Django 3.2.1 on 2022-05-17 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20220516_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogpassword',
            options={'verbose_name': 'Log password', 'verbose_name_plural': 'Logs password'},
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 9, 38, 25, 824377), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 9, 38, 25, 824377), null=True, verbose_name='Última de modificación'),
        ),
    ]
