# Generated by Django 3.2.1 on 2022-05-18 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20220518_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='description_siglo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción siglo'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='name',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 10, 56, 32, 949544), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='description_siglo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción siglo'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 10, 56, 32, 949544), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=70, unique=True, verbose_name='Usuario'),
        ),
    ]
