# Generated by Django 3.2.1 on 2022-05-18 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20220518_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default='Dni', max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 43, 22, 33191), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default='Dni', max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 43, 22, 33191), null=True, verbose_name='Última de modificación'),
        ),
    ]
