# Generated by Django 3.2.1 on 2022-05-18 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20220518_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 18, 42, 37, 458778), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 18, 42, 37, 458778), null=True, verbose_name='Última de modificación'),
        ),
    ]
