# Generated by Django 3.2.1 on 2022-05-19 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0055_auto_20220518_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
            bases=('auth.group',),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='encript_password',
            field=models.BooleanField(default=False, verbose_name='Encript password'),
        ),
        migrations.AddField(
            model_name='user',
            name='encript_password',
            field=models.BooleanField(default=False, verbose_name='Encript password'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 10, 23, 17, 533296), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 10, 23, 17, 533296), null=True, verbose_name='Última de modificación'),
        ),
    ]
