# Generated by Django 3.2.1 on 2022-05-19 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20220519_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email_activated',
            field=models.BooleanField(default=False, verbose_name='Email activado'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 17, 18, 49, 786817), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activated',
            field=models.BooleanField(default=False, verbose_name='Email activado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 17, 18, 49, 786817), null=True, verbose_name='Última de modificación'),
        ),
    ]
