# Generated by Django 3.2.1 on 2022-05-19 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20220519_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='update_password_from_bkoffice',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Contraseña desde backoffice'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_password_from_bkoffice',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Contraseña desde backoffice'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 18, 4, 40, 891866), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 18, 4, 40, 891866), null=True, verbose_name='Última de modificación'),
        ),
    ]
