# Generated by Django 3.2.1 on 2022-05-20 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20220519_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 0, 26, 47, 25439), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 0, 26, 47, 25439), null=True, verbose_name='Última de modificación'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
