# Generated by Django 3.2.1 on 2022-05-20 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20220520_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='last_login',
            field=models.DateTimeField(default=None, null=True, verbose_name='Último inicio'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 11, 21, 41, 117567), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None, null=True, verbose_name='Último inicio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 11, 21, 41, 117567), null=True, verbose_name='Última de modificación'),
        ),
    ]
