# Generated by Django 3.2.1 on 2022-05-23 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20220520_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 15, 7, 32, 882664), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 15, 7, 32, 882664), null=True, verbose_name='Última de modificación'),
        ),
    ]
