# Generated by Django 3.2.1 on 2022-05-26 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0070_auto_20220526_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsAdmin',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('type', models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
            bases=('auth.group',),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 8, 40, 59, 140843), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 8, 40, 59, 140843), null=True, verbose_name='Última de modificación'),
        ),
    ]
