# Generated by Django 3.2.1 on 2022-06-02 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20220526_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsadmin',
            options={'ordering': ['name'], 'verbose_name_plural': 'Roles y permisos'},
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='last_name_manager',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del responsable'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='name_manager',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres del responsable'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 35, 11, 232311), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='last_name_manager',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del responsable'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name_manager',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres del responsable'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 35, 11, 232311), null=True, verbose_name='Última de modificación'),
        ),
    ]
