# Generated by Django 3.2.1 on 2022-06-02 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20220601_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='document_type_manager',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default=None, max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 35, 59, 765241), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='document_type_manager',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte')], default=None, max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 35, 59, 765241), null=True, verbose_name='Última de modificación'),
        ),
    ]
