# Generated by Django 3.2.1 on 2022-06-02 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20220601_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='document_type_manager',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='Dni', max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 44, 30, 646963), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='document_type_manager',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default='Dni', max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 44, 30, 646963), null=True, verbose_name='Última de modificación'),
        ),
    ]
