# Generated by Django 3.2.1 on 2022-06-02 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20220601_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 48, 9, 644399), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 48, 9, 644399), null=True, verbose_name='Última de modificación'),
        ),
    ]
