# Generated by Django 3.2.1 on 2022-06-03 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20220601_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 0, 41, 278533), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=250, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 0, 41, 278533), null=True, verbose_name='Última de modificación'),
        ),
    ]
