# Generated by Django 3.2.1 on 2022-06-03 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20220603_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='token_activation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Token activación'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 14, 13, 74831), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_activation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Token activación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 14, 13, 74831), null=True, verbose_name='Última de modificación'),
        ),
    ]
