# Generated by Django 3.2.1 on 2022-06-07 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20220603_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='cellphone',
            field=models.CharField(max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='document_number',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=30, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='job',
            field=models.CharField(max_length=150, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 12, 12, 16, 530918), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=30, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=150, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 12, 12, 16, 530918), null=True, verbose_name='Última de modificación'),
        ),
    ]
