# Generated by Django 3.2.1 on 2022-06-07 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20220607_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default=None, max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 12, 46, 59, 713152), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default=None, max_length=30, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 12, 46, 59, 713152), null=True, verbose_name='Última de modificación'),
        ),
    ]
