# Generated by Django 3.2.1 on 2022-06-10 15:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_auto_20220607_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Correcto')),
                ('type', models.CharField(choices=[('Unilabs', 'Unilabs'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Cron')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Sincronización',
                'verbose_name_plural': 'Sincronizaciones',
            },
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 10, 8, 8, 214825), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 10, 8, 8, 214825), null=True, verbose_name='Última de modificación'),
        ),
    ]
