# Generated by Django 3.2.1 on 2022-06-10 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20220610_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synchronization',
            old_name='is_staff',
            new_name='is_ok',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 10, 10, 16, 201130), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 10, 10, 16, 201130), null=True, verbose_name='Última de modificación'),
        ),
    ]
