# Generated by Django 3.2.1 on 2024-08-16 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20220610_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreference',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Referencia', 'verbose_name_plural': 'historical Referencias'},
        ),
        migrations.AlterModelOptions(
            name='historicalreferenceadmin',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Administrador', 'verbose_name_plural': 'historical Administradores'},
        ),
        migrations.AlterModelOptions(
            name='historicalreferenceexecutive',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ejecutivo', 'verbose_name_plural': 'historical Ejecutivos'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Usuario', 'verbose_name_plural': 'historical Usuarios'},
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreferenceadmin',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreferenceexecutive',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 16, 13, 11, 18, 300282), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='synchronization',
            name='type',
            field=models.CharField(choices=[('Usuarios', 'Usuarios'), ('Referencia', 'Referencia')], default='Referencia', max_length=30, verbose_name='Cron'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 16, 13, 11, 18, 300282), null=True, verbose_name='Última de modificación'),
        ),
    ]
