# Generated by Django 3.2.25 on 2025-09-28 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreference',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Referencia'},
        ),
        migrations.AlterModelOptions(
            name='historicalreferenceadmin',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Administrador'},
        ),
        migrations.AlterModelOptions(
            name='historicalreferenceexecutive',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ejecutivo'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Usuario'},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='image_id',
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalreferenceadmin',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalreferenceexecutive',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 1, 40, 48, 696047), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(blank=True, default=None, related_name='references', to='users.Reference', verbose_name='Referencias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 1, 40, 48, 696047), null=True, verbose_name='Última de modificación'),
        ),
    ]
