# Generated by Django 3.2.25 on 2025-09-28 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_auto_20250928_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 3, 22, 2, 739133), null=True, verbose_name='Última de modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 3, 22, 2, 739133), null=True, verbose_name='Última de modificación'),
        ),
    ]
