# Generated by Django 3.2.1 on 2021-11-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=45, verbose_name='Clave')),
                ('value', models.TextField(blank=True, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.DeleteModel(
            name='Attention',
        ),
    ]
