# Generated by Django 3.2.1 on 2021-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20211102_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='key',
            field=models.CharField(blank=True, max_length=45, unique=True, verbose_name='Clave'),
        ),
    ]
