# Generated by Django 3.2.1 on 2021-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_information_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=70, unique=True, verbose_name='Asunto')),
                ('emails', models.TextField(blank=True, verbose_name='Correos')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': "Email's",
            },
        ),
    ]
