# Generated by Django 3.2.1 on 2022-04-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='type',
            field=models.CharField(choices=[('admins', 'Administradores'), ('error_luggage', 'Error valijas')], default='type', max_length=40, unique=True, verbose_name='Tipo'),
        ),
    ]
