# Generated by Django 3.2.1 on 2022-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_emails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='emails',
            field=models.TextField(blank=True, verbose_name="Correos (separados por comas ',')"),
        ),
    ]
