# Generated by Django 3.2.1 on 2022-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_emails_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='emails',
            field=models.TextField(blank=True, verbose_name='Correos (separados por comas)'),
        ),
    ]
