# Generated by Django 3.2.1 on 2022-05-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_historicalemails_historicalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='type',
            field=models.CharField(choices=[('admins', 'Administradores'), ('error_luggage', 'Error valijas')], default=None, max_length=40, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalemails',
            name='type',
            field=models.CharField(choices=[('admins', 'Administradores'), ('error_luggage', 'Error valijas')], db_index=True, default=None, max_length=40, verbose_name='Tipo'),
        ),
    ]
