# Generated by Django 3.2.1 on 2024-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20220525_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalemails',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Email', 'verbose_name_plural': "historical Email's"},
        ),
        migrations.AlterModelOptions(
            name='historicalinformation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Información', 'verbose_name_plural': 'historical Información'},
        ),
        migrations.AlterField(
            model_name='emails',
            name='type',
            field=models.CharField(choices=[('error_sync', 'Error sincronización'), ('error_luggage', 'Error valijas')], default=None, max_length=40, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalemails',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemails',
            name='type',
            field=models.CharField(choices=[('error_sync', 'Error sincronización'), ('error_luggage', 'Error valijas')], db_index=True, default=None, max_length=40, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalinformation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
