# Generated by Django 3.2.25 on 2025-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_auto_20240816_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalemails',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Email'},
        ),
        migrations.AlterModelOptions(
            name='historicalinformation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Información'},
        ),
        migrations.AlterField(
            model_name='historicalemails',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalinformation',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
