# Generated by Django 3.2.1 on 2022-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisibleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(blank=True, default=False, null=True, verbose_name='Visible')),
                ('module', models.CharField(choices=[('images', 'Imagenes'), ('result', 'Resultados'), ('luggage', 'Valija'), ('catalog', 'Catalogo')], default='luggage', max_length=40, unique=True, verbose_name='Modulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
    ]
