# Generated by Django 3.2.1 on 2022-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiblemodule',
            name='module',
            field=models.CharField(choices=[('imagenes', 'Imagenes'), ('resultados', 'Resultados'), ('mis-valijas', 'Valija'), ('catalogo-de-pruebas', 'Catalogo'), ('registro-atenciones', 'Registro de atenciones'), ('manual-pre-analitica', 'Manual pre-analitica')], default='luggage', max_length=40, unique=True, verbose_name='Modulo'),
        ),
    ]
