# Generated by Django 3.2.1 on 2022-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_visiblemodule_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiblemodule',
            name='icon',
            field=models.CharField(default='', max_length=40, verbose_name='Icono'),
        ),
    ]
