# Generated by Django 3.2.1 on 2022-03-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_visiblemodule_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiblemodule',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='visiblemodule',
            name='module',
            field=models.CharField(choices=[('imagenes', 'Imágenes'), ('resultados', 'Resultados'), ('mis-valijas', 'Valija'), ('catalogo-de-pruebas', 'Catálogo'), ('registro-atenciones', 'Registro de atenciones'), ('manual-pre-analitica', 'Manual pre-analítica')], default='luggage', max_length=40, unique=True, verbose_name='Modulo'),
        ),
    ]
