# Generated by Django 3.2.1 on 2022-03-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20220324_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiblemodule',
            options={'ordering': ['order'], 'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AddField(
            model_name='visiblemodule',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='visiblemodule',
            name='module',
            field=models.CharField(choices=[('imagenes', 'Imágenes'), ('resultados', 'Resultados'), ('mis-valijas', 'Valija'), ('catalogo-de-pruebas', 'Catálogo'), ('registro-atenciones', 'Registro de atenciones'), ('manual-pre-analitica', 'Manual pre-analítica')], default='luggage', max_length=40, unique=True, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='visiblemodule',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='Titulo'),
        ),
    ]
