# Generated by Django 3.2.1 on 2022-03-31 04:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20220324_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiblemodule',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
