# Generated by Django 3.2.1 on 2022-04-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_visiblemodule_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('icon', models.CharField(default='', max_length=40, verbose_name='Icono')),
                ('title', models.CharField(default='', max_length=40, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='VisibleModule',
        ),
    ]
