# Generated by Django 3.2.1 on 2022-04-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20220404_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module',
            field=models.CharField(choices=[('imagenes', 'Imágenes'), ('resultados', 'Resultados'), ('mis-valijas', 'Valija'), ('catalogo-de-pruebas', 'Catálogo'), ('registro-atenciones', 'Registro de atenciones'), ('manual-pre-analitica', 'Manual pre-analítica'), ('notification', 'Notificaciones')], default='luggage', max_length=40, unique=True, verbose_name='Módulo'),
        ),
    ]
