# Generated by Django 3.2.1 on 2022-04-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_module_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='visible',
        ),
    ]
