# Generated by Django 3.2.1 on 2022-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_remove_module_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='module/image'),
        ),
    ]
