# Generated by Django 3.2.1 on 2022-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_module_icon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['the_order'], 'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AddField(
            model_name='module',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
