# Generated by Django 3.2.1 on 2022-04-25 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0011_auto_20220424_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalModule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('module', models.CharField(choices=[('imagenes', 'Imágenes'), ('resultados', 'Resultados'), ('mis-valijas', 'Valija'), ('catalogo-de-pruebas', 'Catálogo'), ('registro-atenciones', 'Registro de atenciones'), ('manual-pre-analitica', 'Manual pre-analítica'), ('notification', 'Notificaciones')], db_index=True, default='luggage', max_length=40, verbose_name='Módulo')),
                ('icon', models.CharField(default='', max_length=40, verbose_name='Icono')),
                ('icon_image', models.TextField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='', max_length=40, verbose_name='Titulo')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modulo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
