# Generated by Django 3.2.1 on 2024-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_historicalmodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmodule',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Modulo', 'verbose_name_plural': 'historical Modulos'},
        ),
        migrations.AlterField(
            model_name='historicalmodule',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
