# Generated by Django 3.2.1 on 2022-03-31 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('manual', models.FileField(blank=True, null=True, upload_to='analytical/pdf', verbose_name='Manual')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Pre-analitica',
                'verbose_name_plural': 'Analiticas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StageAnalytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('analytical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_stage', to='analytical.analytical', verbose_name='Analitica')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Descripción')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Duración')),
                ('video', models.CharField(max_length=200, null=True, verbose_name='URL video')),
                ('image', models.ImageField(null=True, upload_to='video-analytical/image', verbose_name='Imagen (600px x 600px)')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('analytical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_video', to='analytical.analytical', verbose_name='Analítica')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StagePageAnalytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='analytical/image', verbose_name='Imagen')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='analytical/image', verbose_name='Imagen Mobile')),
                ('description_image', models.TextField(blank=True, null=True, verbose_name='Descripción Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_page', to='analytical.stageanalytical', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Titulo')),
                ('page', models.IntegerField(blank=True, verbose_name='Pagina')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_record', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
                'ordering': ['-id'],
            },
        ),
    ]
