# Generated by Django 3.2.1 on 2024-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0002_historicalanalytical_historicalvideoanalytical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalanalytical',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pre-analitica', 'verbose_name_plural': 'historical Analiticas'},
        ),
        migrations.AlterModelOptions(
            name='historicalvideoanalytical',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Video', 'verbose_name_plural': 'historical Videos'},
        ),
        migrations.AlterField(
            model_name='historicalanalytical',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvideoanalytical',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
