# Generated by Django 3.2.25 on 2025-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0003_auto_20240816_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalanalytical',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pre-analitica'},
        ),
        migrations.AlterModelOptions(
            name='historicalvideoanalytical',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Video'},
        ),
        migrations.AlterField(
            model_name='historicalanalytical',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalvideoanalytical',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
